import { create } from "zustand";
import * as api from "../api/client.ts";
import { ApiRequestError } from "../api/client.ts";
import type { AiAspectRatio, AiVideoProgress, CaptionSegment, SourceRect, StockSearchResult } from "../api/client.ts";
import type { Command } from "../commands/index.ts";
import {
  AddCaptionsCommand,
  AddClipCommand,
  AddTrackCommand,
  BatchCommand,
  buildTextAnimationCommand,
  buildTextStylePatchCommand,
  buildTextStylePresetCommand,
  DuplicateClipsCommand,
  ExtractAudioCommand,
  isAutoGeneratedCaptionsTrackName,
  RemoveTrackCommand,
  ReplaceClipAssetCommand,
  SwapClipAssetCommand,
} from "../commands/index.ts";
import { OUTRO_DURATION_SECONDS } from "../export/outro.ts";
import type { Language } from "../i18n/translations.ts";
import { translateText } from "../i18n/translations.ts";
import type { PlaybackEngine } from "../playback/PlaybackEngine.ts";
import { createColorAsset, createTextAsset, findAsset, findClip, sequenceDuration } from "../project/createProject.ts";
import type { TextStylePreset } from "../project/textStylePresets.ts";
import type { Asset, Clip, Project, TextStyle } from "../project/types.ts";
import type { ClipOverride } from "../timeline/groupMove.ts";
import { defaultClipDuration, EditError, trackKindForAsset } from "../timeline/operations.ts";
import { nonOverlappingPointStart, nonOverlappingStart } from "../timeline/queries.ts";
import { snapToFrame } from "../timeline/time.ts";
import { UndoStack } from "../undo/UndoStack.ts";

const LANGUAGE_STORAGE_KEY = "vcut-language";

/** SSR-safe: this module's very first render (server, or the first client tick before hydration) has
 *  no `window` — same guard pattern `VCutApp.tsx`'s own `timelineHeight` initializer already uses
 *  for the same reason. Falls back to English on any unexpected read error (a disabled/private-mode
 *  localStorage throwing is a real possibility, not just theoretical) rather than crashing the app
 *  over a UI-language preference. */
function readStoredLanguage(): Language {
  if (typeof window === "undefined") return "en";
  try {
    return window.localStorage.getItem(LANGUAGE_STORAGE_KEY) === "km" ? "km" : "en";
  } catch {
    return "en";
  }
}

/** How long after the last edit an autosave fires. Long enough that a burst of edits (dragging a
 *  clip produces many) collapses into one write, short enough that little is at risk if the app
 *  closes unexpectedly. */
const AUTOSAVE_DELAY_MS = 1500;

/** The timeline's starting zoom level, and what Ctrl/⌘+0 resets it back to. */
const DEFAULT_PIXELS_PER_SECOND = 60;

export type StatusTone = "info" | "error";

/** One AI image/video generation, as `AiGeneratePanel.tsx` renders it — see `EditorState.aiGenerations`'s
 *  own doc comment for why this lives in the store rather than component state. `aspectRatio` is kept
 *  even after the asset itself exists so the tile can show the right SHAPE while still generating
 *  (before there's a thumbnail to measure), not just after. `progress`/`stage` only ever apply to video
 *  (image generation is a single request/response with no partial progress to report). */
export interface AiGenerationItem {
  id: string;
  kind: "image" | "video";
  prompt: string;
  aspectRatio: AiAspectRatio;
  status: "generating" | "done" | "failed";
  asset?: Asset;
  error?: string;
  progress?: number;
  stage?: string;
}

export interface EditorState {
  projectId: string | null;
  project: Project | null;
  loading: boolean;
  loadError: string | null;
  /** The HTTP status behind `loadError`, when it came from a real server response — `401` specifically
   *  is what `VCutApp.tsx`'s own error screen checks to offer an actual "Sign In" action instead of a
   *  "Try again" that would just fail identically (the session is gone, not the request). Confirmed a
   *  real, reported dead end: a session expiring mid-use (the access token's own lifetime elapsing
   *  while the tab/PWA sat idle, e.g. overnight) hit this exact screen with no way back in short of
   *  navigating away from the project entirely to find a sign-in entry point elsewhere. `null` for
   *  every other failure (network error, a non-auth `ApiError`, ...), where "Try again" is genuinely
   *  the right — and only — recovery action. */
  loadErrorStatus: number | null;

  /** Timeline position in seconds — the single source of truth for both the preview and the
   *  playhead, so they can never disagree. */
  playhead: number;
  playing: boolean;
  /** The export range — `null` on either end means "the full timeline" (from 0 / to
   *  `sequenceDuration`), matching this app's general "absent means the default" convention. Session-
   *  only: NOT part of `project`, never saved to `project.json`, and never pushed to the undo stack —
   *  like `pixelsPerSecond`/`activeTrackId`, this is working-session UI state (which slice of the
   *  timeline you're currently choosing to render out), not a property of the edit itself. Order isn't
   *  enforced at write time (setting a start past the current end is allowed) — every consumer reads
   *  through `exportRange()` below, which sorts and clamps, so a momentarily "backwards" pair here can
   *  never reach the UI or the export pipeline as an invalid range. */
  exportRangeStart: number | null;
  exportRangeEnd: number | null;
  /** Horizontal timeline scale, in pixels per second. */
  pixelsPerSecond: number;
  selectedClipIds: string[];
  /** Which track a newly-dropped clip lands on when the user doesn't pick one explicitly. */
  activeTrackId: string | null;
  /** While `TransformHandles`/`TextTransformHandles` are mid-drag, every clip's transform/style they'd
   *  commit if released RIGHT NOW — the actively-dragged clip PLUS every other clip in a multi-select
   *  group move (see `timeline/groupMove.ts`). Read by `PlaybackEngine` (via
   *  `PlaybackHost.getLiveOverrides`) so the canvas itself tracks the drag — the whole group, not just
   *  the one clip under the pointer — instead of only the handle box(es) overlaid on top of it.
   *  Deliberately NOT part of `project` (so dragging never touches the undo stack until release, same
   *  as the local-preview-then-single-commit pattern those components already use) and not persisted
   *  — purely a live rendering hint, cleared the instant the drag ends. */
  livePreviewOverrides: ClipOverride[];

  /** Seconds every OTHER selected clip should shift by, live, while ONE of them is being dragged along
   *  the Timeline's own time axis — `null` when no such drag is in progress. `TimelineClip`'s own
   *  local-preview-then-single-commit pattern already moves the clip actually under the pointer (its
   *  own component-local `preview` state), but every OTHER selected clip is a SEPARATE component
   *  instance with no way to know a group drag is happening at all — without this, only the one clip
   *  under the pointer visibly moved during the drag itself, with the rest snapping into place all at
   *  once only once the mouse was released, which reads as "only one clip can be moved" even though the
   *  committed result (via the `BatchCommand` `TimelineClip`'s own `onUp` already builds) was always
   *  correct. Same "ephemeral view state, not part of `project`, not persisted" precedent as
   *  `livePreviewOverrides` above — this is its Timeline-space (1D, seconds) counterpart to that one's
   *  canvas-space (2D, pixels) `ClipOverride[]`; kept as a separate, simpler field rather than folding
   *  into `livePreviewOverrides` since every group member shifts by the exact same delta (no per-clip
   *  position to track), and `TimelineClip` needs to read it independent of whether `PlaybackEngine`
   *  is even attached. */
  groupMoveDelta: number | null;

  /** Live value of an in-progress Mixer track-fader drag — `null` when no track fader is being
   *  dragged. Same "ephemeral view state, not part of `project`, not persisted, cleared on commit"
   *  precedent as `livePreviewOverrides`, just scoped to gain rather than transform: `MixerDialog`
   *  wires a `NumberField`'s `onPreview` to this (continuous, no undo entry) and `onCommit` to
   *  `run(new SetTrackGainCommand(...))` (once, on release) — `PlaybackEngine`'s
   *  `getLiveTrackGainPreview` host getter reads it once per tick so the audio actually changes while
   *  you drag, not just once you let go. Kept as its own field rather than folding into
   *  `livePreviewOverrides` (which is clip-keyed, for the canvas) since only one fader can ever be
   *  dragged at a time — no array needed. */
  livePreviewTrackGain: { trackId: string; gain: number } | null;
  /** Same relationship as `livePreviewTrackGain`, for the Mixer's master fader. */
  livePreviewMasterGain: number | null;
  /** Same relationship as `livePreviewTrackGain`, for an in-progress Mixer pan-knob drag. */
  livePreviewTrackPan: { trackId: string; pan: number } | null;
  /** Silences the WHOLE live-preview mix (every track, master fader included) without touching a single
   *  gain/mute value in the actual project — deliberately separate from `livePreviewMasterGain` (which
   *  the Mixer's own master-fader DRAG owns exclusively, resetting to `null` on every commit and on
   *  unmount; sharing it here would mean opening/closing the Mixer panel could silently clear a mute the
   *  user turned on somewhere else). The one real use case this exists for: recording a voiceover while
   *  the sequence keeps playing for reference (`VoiceoverRecorder`'s own toolbar button sits right next
   *  to the toggle that flips this) — muting playback while STILL recording/monitoring avoids the
   *  existing audio bleeding back into the mic through the speakers. Read by `Preview.tsx`'s
   *  `getLiveMasterGainPreview`, which is the one place both this and the Mixer's own live override are
   *  reconciled into the single number `PlaybackEngine` actually applies. Never persisted, never
   *  exported — closing/reopening the project (or exporting) always hears the real mix. */
  previewMuted: boolean;

  /** The live `PlaybackEngine` instance itself — set once by `Preview.tsx`'s engine-creation effect,
   *  cleared back to `null` in that same effect's cleanup (alongside its existing `engine.detach()`
   *  call). This is the first time anything outside `Preview.tsx` has ever needed to read FROM the
   *  engine rather than only write to it via `livePreviewTrackGain`-style fields — the Mixer's level
   *  meters need a live per-track/master dB reading every animation frame, which has no sensible
   *  "store field the engine polls and writes into" shape the way a preview override does (that would
   *  mean writing to Zustand state 60 times a second, forcing a re-render on every meter tick).
   *  Instead, `LevelMeter` reads THIS field once (cheap — it only changes once per mount, not every
   *  frame) to get a reference to the engine, then calls `engine.getTrackLevelDb`/`getMasterLevelDb`
   *  directly from its own self-contained `requestAnimationFrame` loop, writing straight to a DOM ref —
   *  completely outside React's render cycle, the same way `PlaybackEngine`/`AudioMixEngine` themselves
   *  already operate. */
  playbackEngine: PlaybackEngine | null;

  dirty: boolean;
  saving: boolean;
  lastSavedAt: number | null;

  canUndo: boolean;
  canRedo: boolean;
  undoLabel: string | null;
  redoLabel: string | null;

  status: { message: string; tone: StatusTone } | null;
  importing: boolean;
  /** Every AI image/video generation this session, newest first — lives HERE rather than as local
   *  `AiGeneratePanel` state because that component can genuinely unmount mid-generation: on mobile,
   *  the "AI" tab only exists inside the bottom media SHEET (`VCutApp.tsx`'s own `mobileSheet`), which
   *  unmounts entirely the instant a user taps a different toolbar button — a component-local history
   *  (and, worse, a component-owned `watchAiVideo` SSE subscription) would vanish and silently orphan
   *  a job that was still running server-side. Store-level state has no such lifecycle: it survives
   *  exactly as long as the editor session does, same as `project` itself. */
  aiGenerations: AiGenerationItem[];
  /** Which "My Sounds" import is currently in flight — disables `SfxPanel`'s own import button so a
   *  second click can't fire a second upload while the first is still running. Session-only, same
   *  category as `importing` (this project's own separate flag, not shared with it, since a plain
   *  media import and a sound-effect-library import are two independent operations a user could
   *  plausibly trigger at the same time). */
  importingSfx: boolean;
  /** Same role as `importingSfx`, for the Inspector's "My LUTs" import button instead. */
  importingLut: boolean;
  /** Same role as `importingSfx`, for the Inspector's "My Fonts" import button instead. */
  importingFont: boolean;

  /** Which mobile-only bottom-row "sheet" is currently showing in place of Timeline — `null` means
   *  Timeline itself (the default, and the only state that ever applies at `lg`+, where these two
   *  toolbar buttons don't even render — see `VCutApp.tsx`'s own comment on why Media/Properties have
   *  no permanent side column below that breakpoint). Session-only, same category as `activeTrackId`:
   *  a working-session UI choice, never part of `project`, never undo-tracked. Lives in the STORE
   *  (not local `VCutApp` state, which is where this started) because `TimelineClip`'s own double-
   *  tap-to-edit gesture needs to open Properties from deep inside the Timeline tree, with no prop-
   *  drilling path back up to `VCutApp` — the same "needs to be reachable from somewhere with no direct
   *  component relationship to the owner" reasoning `playbackEngine`'s own doc comment gives for living
   *  here instead of as a plain prop. */
  mobileSheet: "media" | "inspector" | null;
  setMobileSheet: (next: "media" | "inspector" | null) => void;

  /** The live `<canvas>` `Preview.tsx` currently has attached to its `PlaybackEngine` — set by that
   *  same effect that calls `engine.attach(canvas)`, cleared back to `null` on unmount, mirroring
   *  `playbackEngine`'s own set/clear lifecycle exactly (both exist for the identical reason: giving a
   *  component OUTSIDE `Preview.tsx` a way to reach something `Preview.tsx` owns, with no sensible
   *  prop-drilling path). `ScopesPanel`'s own waveform/vectorscope/histogram readout is the one
   *  consumer — it samples this canvas's own live pixels on its own independent `requestAnimationFrame`
   *  loop rather than being pushed frames, which is what lets it keep updating while scrubbing (not
   *  just during real playback) with zero coupling to `PlaybackEngine`'s own render loop. */
  previewCanvas: HTMLCanvasElement | null;
  setPreviewCanvas: (canvas: HTMLCanvasElement | null) => void;

  /** UI chrome language — the first persisted (localStorage) preference in this store; everything
   *  else here is explicitly session-only. Never affects `project` (a text clip's own font/content is
   *  unrelated project data, not UI chrome), matching how a theme choice would be scoped. */
  language: Language;
  setLanguage: (language: Language) => void;

  load: (projectId: string, projectName?: string) => Promise<void>;
  run: (command: Command) => void;
  undo: () => void;
  redo: () => void;
  save: () => Promise<void>;

  setPlayhead: (seconds: number) => void;
  setPlaying: (playing: boolean) => void;
  togglePlay: () => void;
  stepFrames: (frames: number) => void;
  /** `exportRangeStart`/`End` resolved against the CURRENT project — clamped to `[0, sequenceDuration]`
   *  and sorted (the smaller of the two is always `start`) — so every consumer (the Timeline's own
   *  markers/shading, `ExportDialog`) reads one always-valid range regardless of what order the two
   *  points were set in, or whether the timeline has since gotten shorter than a previously-set point. */
  exportRange: () => { start: number; end: number };
  setExportRangeStart: (seconds: number | null) => void;
  setExportRangeEnd: (seconds: number | null) => void;
  /** Back to "the full timeline" — both ends absent. */
  clearExportRange: () => void;
  setPixelsPerSecond: (value: number) => void;
  zoomBy: (factor: number) => void;
  resetZoom: () => void;
  select: (clipIds: string[]) => void;
  /** Adds `clipId` to the selection if it isn't already selected, or removes it if it is — the
   *  Ctrl/Cmd+click gesture, working identically regardless of which track or clip kind the clip is
   *  on, which is what makes selecting across video/text/audio clips together possible. */
  toggleSelect: (clipId: string) => void;
  setActiveTrack: (trackId: string) => void;
  setLivePreviewOverrides: (overrides: ClipOverride[]) => void;
  setGroupMoveDelta: (delta: number | null) => void;
  setLivePreviewTrackGain: (value: { trackId: string; gain: number } | null) => void;
  setLivePreviewMasterGain: (value: number | null) => void;
  setLivePreviewTrackPan: (value: { trackId: string; pan: number } | null) => void;
  togglePreviewMuted: () => void;
  setPlaybackEngine: (engine: PlaybackEngine | null) => void;

  /** Live "recording in progress" indicator for `VoiceoverRecorder` — a growing placeholder in the
   *  target track's lane while capturing, since there's no real `Clip`/asset to render yet (the asset
   *  only comes into being once the recording is imported after stop). Session-only: not part of
   *  `project`, never saved, never undo-tracked — a pure rendering hint, same category as
   *  `livePreviewOverrides`. `phase: "recording"` grows live with `elapsedSeconds`; `"finalizing"`
   *  freezes at the last length while the stopped take is being imported and placed, so the indicator
   *  doesn't just vanish and pop back in a moment later as a real clip. */
  recording: { trackId: string; start: number; elapsedSeconds: number; phase: "recording" | "finalizing" } | null;
  beginRecordingIndicator: (trackId: string, start: number) => void;
  updateRecordingElapsed: (elapsedSeconds: number) => void;
  finalizeRecordingIndicator: () => void;
  clearRecordingIndicator: () => void;
  /** Picks where a new voiceover recording should land, without creating anything: an empty unlocked
   *  audio track first (so a fresh take never overlaps existing content), else an unlocked audio track
   *  that already holds a prior recording (grouping takes together rather than mixing into a music/SFX
   *  track), else the first unlocked audio track at all, else null — meaning the caller should create
   *  a new one. */
  pickVoiceoverTrack: () => string | null;
  /** Combines `pickVoiceoverTrack` (creating a new audio track if none qualifies) with marking the
   *  live recording indicator there — called once capture actually begins (mic permission granted).
   *  Returns the target track/start so the caller can place the REAL clip at the exact same spot once
   *  the take finishes, keeping the live indicator and the final clip in perfect agreement (no jump
   *  to a different position once the true duration is known). Null only if no project is loaded. */
  beginVoiceoverRecording: () => { trackId: string; start: number } | null;

  /** Live position of an in-progress touch-driven asset drag from the Media Library — native HTML5
   *  drag-and-drop never fires from touch input at all (confirmed dead on iOS Safari in particular),
   *  so `MediaLibrary`'s own pointer-based drag writes here on every move, and `Timeline` reads it to
   *  draw the same drop-target track highlight a mouse drag already gets for free from the browser's
   *  native dragover/drop. Null when nothing is being dragged. */
  assetDrag: { assetId: string; clientX: number; clientY: number } | null;
  setAssetDrag: (drag: EditorState["assetDrag"]) => void;

  /** A right-clicked clip's own screen position, for `ClipContextMenu` (rendered once, inside
   *  `StatusBar`, which already computes every "can this tool act on the current selection" flag the
   *  bottom toolbar itself uses — routed through the store rather than prop-drilled from
   *  `TimelineClip`, which has no direct path to that component several levels up the tree, the same
   *  "far-apart components coordinate through global state" shape `assetDrag`/`mobileSheet` above
   *  already use). `clipId` is set for completeness/future use (e.g. a future per-clip-specific menu
   *  item) — today's menu items all act on `selectedClipIds` instead, already updated by the
   *  `contextmenu` handler that sets this before the menu ever reads it. Null when no menu is open. */
  contextMenu: { x: number; y: number; clipId: string } | null;
  setContextMenu: (menu: EditorState["contextMenu"]) => void;

  /** A NEW text clip's content, being composed BEFORE anything is placed on the timeline at all —
   *  `NewTextComposer` (mounted once, near the app's root) reads this to show its own input; `null`
   *  means nothing is currently being composed. Deliberately not the same mechanism as editing an
   *  EXISTING clip (`TextTransformHandles`'s own `editingAssetId`/on-canvas textarea): that whole
   *  mechanism resolves against `selectedClipIds` AND requires the clip to be the one actually under
   *  the current playhead (`clipAtTime` — see `TextTransformHandles`'s own `resolved` doc comment) —
   *  a real, confirmed bug in an earlier version of this feature: `nonOverlappingStart` nudging a new
   *  clip's placement away from the exact playhead (to avoid overlapping something already there) made
   *  it silently un-resolvable to that mechanism, so its own auto-edit-on-create step never fired at
   *  all — the clip existed, empty, with no way to type into it short of a manual double-click. This
   *  compose-first flow sidesteps that class of bug entirely by never creating anything (so there is no
   *  clip/selection/playhead alignment to get wrong) until real, confirmed text exists — see
   *  `commitComposedText`'s own doc comment for the actual creation step. */
  /** `trackId` is set only when composing was started FROM a specific empty track's own "+" button
   *  (`Timeline.tsx`) — the clip must land on THAT track, not wherever `commitComposedText`'s own
   *  generic "first unlocked text track, or a fresh one" fallback would otherwise put it. Absent for
   *  the toolbar's Text button, which has no specific track in mind. `content` is the live-typed draft
   *  — `NewTextComposer`'s input writes it on every keystroke (via `setComposeTextContent`) rather than
   *  keeping it as the input's own local state, so `Preview`'s `getProject()` can read it back and
   *  render a live phantom clip on the canvas while composing, before anything real exists to render.
   *  Starts `""` the instant composing is armed (see `setComposeText`). */
  composeText: { style: TextStyle; trackId?: string; content: string } | null;
  /** Arms composing with a style (and, from an empty track's own "+" button, a specific `trackId`) —
   *  `content` always starts empty here; `setComposeTextContent` is what tracks it live afterward. */
  setComposeText: (compose: { style: TextStyle; trackId?: string }) => void;
  /** Live-updates the draft text while composing — see `composeText.content`'s own doc comment for why
   *  this lives in the store rather than as `NewTextComposer`'s own local input state. No-op if nothing
   *  is currently being composed. */
  setComposeTextContent: (content: string) => void;
  /** Creates and places a new text clip with whichever content/style/track `composeText` currently
   *  holds (see that field's own doc comment), then clears `composeText` — the actual "add text" step,
   *  deferred until here specifically so it never runs at all for text nobody actually typed. Blank/
   *  whitespace-only content is treated as "the user backed out" and adds nothing, same outcome as
   *  calling `cancelComposeText` instead — matches the earlier, since-removed auto-cancel design's own
   *  intent, just reached by never creating the clip in the first place rather than deleting it again a
   *  moment later. No-op (but still clears `composeText`) if nothing is currently being composed. */
  commitComposedText: () => void;
  /** Backs out of composing a new text clip without creating anything — same as confirming with empty
   *  content, just via an explicit dismiss (tapping away, Escape) rather than the confirm button. */
  cancelComposeText: () => void;

  /** "Remove Object" tool state — session-only, never part of `project`, same category as
   *  `livePreviewOverrides`/`assetDrag` above. `removeObjectArmedClipId` is set by the Inspector's
   *  "Draw region" button and read by `RemoveObjectOverlay` to know it should start accepting a
   *  drag-to-draw gesture on the Preview canvas for that specific clip; it's cleared the moment a
   *  rect is committed (or the drawing gesture is abandoned). `removeObjectRect` is the committed
   *  rectangle (in the SOURCE asset's own pixel space, not screen space — see `maskGeometry.ts`),
   *  kept per-clip so switching selection away and back doesn't lose it. */
  removeObjectArmedClipId: string | null;
  removeObjectRect: (SourceRect & { clipId: string }) | null;
  armRemoveObject: (clipId: string) => void;
  setRemoveObjectRect: (clipId: string, rect: SourceRect) => void;
  clearRemoveObject: () => void;
  /** Registered imperatively by `Timeline` (the only component that knows its own scroll offset and
   *  track-row geometry) so `MediaLibrary`'s pointer drag can hit-test an arbitrary screen point
   *  against timeline tracks on release, without either component reaching into the other's DOM
   *  internals. Returns the track and time a drop at that point would land on, or null if the point
   *  isn't over a track row (or the new-track row) at all. Null until `Timeline` mounts.
   *  `assetId` (the asset being dropped, if known) lets the resolver create a fresh track of the
   *  right kind on the fly when the drop lands on the "add track" row below the last real one — see
   *  its own comment in `Timeline.tsx`. */
  resolveTimelineDropTarget:
    | ((clientX: number, clientY: number, assetId?: string) => { trackId: string; time: number } | null)
    | null;
  setResolveTimelineDropTarget: (resolver: EditorState["resolveTimelineDropTarget"]) => void;

  /** Resolves to the successfully-imported assets (empty on total failure) — callers that need to do
   *  something with the result (VoiceoverRecorder placing its recording straight on the timeline)
   *  can, while every other caller (plain drag-drop/file-picker import) is free to still ignore it.
   *  `hiddenFromLibrary`: stamped onto every asset from this call (see `Asset.hiddenFromLibrary`'s own
   *  comment) — used by `VoiceoverRecorder` so a quick take doesn't clutter the Media Library. */
  importFiles: (files: File[], options?: { hiddenFromLibrary?: boolean }) => Promise<Asset[]>;
  /** Downloads one chosen Pixabay stock search result server-side and lands it in `project.assets` —
   *  same "not undo-able, an import is more like an asset creation than a timeline edit" reasoning
   *  `importFiles` itself follows. Singular (one result at a time), matching a user clicking exactly
   *  one search tile — `StockSearchPanel.tsx` is this action's only caller. Returns `null` on failure
   *  (surfaced via `setStatus`, same convention every other import path here uses) rather than
   *  throwing, so a caller never needs its own try/catch just to keep the UI responsive after one bad
   *  download. */
  importStockResult: (result: StockSearchResult) => Promise<Asset | null>;
  /** Generates one image from a prompt (`ai-image/route.ts`, Replicate's Flux Schnell), tracking it as a
   *  new `aiGenerations` entry throughout (see that field's own doc comment) and landing the result in
   *  `project.assets` (`hiddenFromLibrary`, same reasoning `importFiles`'s own comment gives — a
   *  generation belongs in the AI tab's own history, not duplicated into "My Media" too) once it
   *  succeeds. Failures patch that same entry to `status: "failed"` rather than throwing or returning
   *  anything — `AiGeneratePanel.tsx` reads the outcome back off `aiGenerations`, same as it does while
   *  the request is still running. */
  generateAiImage: (prompt: string, aspectRatio: AiAspectRatio) => Promise<void>;
  /** Starts an AI video generation job (`ai-video/route.ts`, Replicate's Seedance 2.0) as a new
   *  `aiGenerations` entry, watches it via SSE, and patches that entry's progress/result as it comes in
   *  — the video equivalent of `generateAiImage` above, just job-based instead of a single request/
   *  response (see `ai-video/route.ts`'s own comment on why). Single-flight: starting a new one while
   *  one is already running isn't exposed in the UI (the Generate button becomes Cancel instead), so
   *  this doesn't guard against it itself. */
  startAiVideoGeneration: (prompt: string, aspectRatio: AiAspectRatio) => Promise<void>;
  /** Cancels whichever AI video job `startAiVideoGeneration` most recently started, if any is still
   *  running — mirrors `cancelInpaint`'s own "racing the job's own completion is normal" tolerance. */
  cancelAiVideoGeneration: () => void;
  removeAsset: (asset: Asset) => Promise<void>;
  /** Imports one file into the project's own reusable "My Sounds" library (`project.customSfx`) —
   *  same "not undo-able, an import is more like an asset creation than a timeline edit" reasoning
   *  `importFiles` itself already follows, just against a separate library array instead of
   *  `project.assets` (see `CustomSfxAsset`'s own doc comment for why the two are kept apart). Errors
   *  surface via `setStatus`, matching `importFiles`'s own failure handling. */
  importSfx: (file: File) => Promise<void>;
  /** Removes one "My Sounds" entry — same "not undo-able" reasoning as `importSfx`/`removeAsset`. Does
   *  NOT touch any clip already placed from it (that clip references a real, separate `Asset` the
   *  import already copied — see `CustomSfxAsset`'s own doc comment), only the reusable library entry
   *  itself. */
  removeSfx: (id: string) => Promise<void>;
  /** Imports a `.cube` file into the project's own LUT library (`project.luts`) — same "not undo-able,
   *  an import is more like an asset creation than a timeline edit" reasoning as `importSfx`, just
   *  against a different library array. Errors surface via `setStatus`, matching `importSfx`'s own
   *  failure handling. */
  importLut: (file: File) => Promise<void>;
  /** Removes one LUT library entry, cascading `lutId: undefined` across every clip that referenced it
   *  — same "not undo-able" reasoning as `removeSfx`, but (unlike a removed SFX, which never touches a
   *  placed clip at all) this genuinely can change how existing clips render, which is exactly why the
   *  server does the cascade and hands back the fully-updated project rather than this just dropping
   *  the library entry locally. */
  removeLut: (id: string) => Promise<void>;
  /** Imports a `.ttf`/`.otf` file into the project's own custom-font library (`project.customFonts`)
   *  — same shape as `importLut`, just against `fonts/route.ts`. A newly-imported font is immediately
   *  selectable from the Inspector's Font dropdown (see `resolveFont`'s own doc comment for how a
   *  clip's `fontFamily` id resolves against this library). */
  importFont: (file: File) => Promise<void>;
  /** Removes one custom-font library entry — no clip-level cascade needed (see `fonts/route.ts`'s own
   *  `DELETE` doc comment: `fontById`'s existing fallback already covers a clip left pointing at a
   *  since-removed font), but still applies the server's own returned project rather than filtering
   *  locally, the same "server is authoritative" reasoning `removeLut` gives. */
  removeFont: (id: string) => Promise<void>;
  /** Creates a color-matte asset AND immediately places it as a clip at the playhead — same
   *  "lands the result somewhere visible in one action" shape `commitComposedText` gives the Text
   *  tool, just on a VIDEO track (a color matte is just a video-track clip whose source is a solid
   *  fill — see `Asset.color`'s own doc comment) instead of a text one. */
  addColorAtPlayhead: (color: string) => void;
  /** `avoidOverlap`: place at the playhead only if that spot is actually free, otherwise right after
   *  whichever clip is actually in the way instead of carving into it — see `nonOverlappingStart`'s
   *  own comment for why a "quick add" caller (Text/Record) needs this and a deliberate manual
   *  placement (double-click a library asset) doesn't. Defaults to false, preserving today's
   *  exact-playhead placement for that manual path. Returns the new clip's id (or `null` if nothing
   *  was actually added — no such asset, no unlocked track of the right kind); every caller besides
   *  `commitComposedText` ignores the return value, unaffected by it existing. */
  addAssetAtPlayhead: (assetId: string, trackId?: string, options?: { avoidOverlap?: boolean }) => string | null;
  /** Duplicates every currently-selected clip (see `DuplicateClipsCommand`'s own doc comment for
   *  exactly where each copy lands and why) as one undo-able step, then selects the fresh copies —
   *  the same "the thing you just created is what's now selected" behavior `commitComposedText` and a
   *  freshly-imported/dropped asset both already give. */
  duplicateSelectedClips: () => void;
  /** Detaches `clipId`'s own embedded audio onto a new clip on an audio track (see
   *  `ExtractAudioCommand`'s own doc comment for exactly how/where it lands), then selects the new
   *  clip — same "what you just created is what's now selected" precedent `duplicateSelectedClips`
   *  and a fresh import/drop already follow. */
  extractAudioFromClip: (clipId: string) => void;
  /** Applies a style preset to every currently-selected TEXT clip at once, as one undo-able step (see
   *  `BatchCommand`'s own doc comment) — the toolbar Text-tool/Script/Captions flows only choose a
   *  style at CREATION time; this is the equivalent for clips that already exist. A clip on the
   *  selection that isn't text is silently skipped, same "not every selected clip has to qualify"
   *  precedent `DuplicateClipsCommand` already sets for locked tracks. */
  applyTextStylePresetToSelection: (preset: TextStylePreset) => void;
  /** Same shape as `applyTextStylePresetToSelection`, for `Clip.textAnimation` instead — the toolbar's
   *  promoted Animation tool (and Inspector's own multi-select panel) both call this so a whole
   *  multi-text-clip selection gets one animation type in one undo step. Scoped to TYPE only —
   *  per-clip `speed`/`highlightColor` fine-tuning stays single-clip, Inspector-only. */
  applyTextAnimationToSelection: (animation: Clip["textAnimation"] | null) => void;
  /** Merges `patch` onto every selected TEXT clip's own CURRENT style independently, as one undo-able
   *  step — the font/size/alignment counterpart to `applyTextStylePresetToSelection` (which replaces
   *  the whole style, deliberately never touching these three fields — see `TextStylePreset`'s own
   *  doc comment for why). Each clip keeps everything else about its own look; only the patched
   *  field(s) change. */
  patchTextStyleForSelection: (patch: Partial<TextStyle>) => void;
  /** Creates a new text asset and adds it to the library — same "not undo-able, an asset creation is
   *  more like an import than an edit" reasoning as `importFiles`. `content` defaults to empty (used
   *  by `Timeline.tsx`'s empty-track "+" button, which arms `composeText` separately rather than
   *  passing content here directly); `commitComposedText` passes the real, already-confirmed text
   *  straight through instead. Returns the new asset's id so a caller can immediately place it (see
   *  `addAssetAtPlayhead`) without a second lookup right after creating it. */
  addTextAsset: (style?: TextStyle, content?: string) => string | null;
  /** Renames the project itself (`project.name` — what VCut's own home page lists it by), not any
   *  individual clip/asset. Same "not undo-able, a metadata edit rather than a timeline edit" category
   *  as `addTextAsset` — Ctrl+Z undoing a rename in the middle of unrelated clip edits would be a
   *  surprising thing for the undo stack to track. Falls back to "Untitled" for an empty/whitespace-
   *  only name, matching `createProject`'s own default. */
  renameProject: (name: string) => void;
  /** Lands a "Remove Object" job's finished result directly onto the clip it processed — genuinely
   *  goes through `run()` (see `ReplaceClipAssetCommand`'s own doc comment), so it's one undo-able
   *  step: Ctrl+Z puts the original clip back exactly as it was, not just "removes the new asset from
   *  the library while leaving the swapped clip changed." Used to just add the result to the Media
   *  Library and leave the clip untouched — a deliberate v1 scope cut, closed once there WAS a single
   *  obviously-correct "replace this clip" behavior to automate (see the command's own doc comment for
   *  the sourceIn/sourceOut reasoning). */
  landInpaintedAsset: (clipId: string, asset: Asset) => void;
  /** Lands an Auto Captions job's finished segments as real text assets + clips on a new text track —
   *  unlike `landInpaintedAsset`, this genuinely goes through `run()` (see `AddCaptionsCommand`'s own
   *  doc comment for why): a caption pass creates its assets AND places them in one user-facing
   *  action, so it undoes as one step too, rather than the asset-creation-is-permanent convention
   *  every other asset-adding action here follows. Also selects the whole new batch, jumps the
   *  playhead to the first caption, and closes whichever mobile sheet (Media/Properties) triggered the
   *  job — the caller (`AutoCaptionsDialog`/Inspector's `AutoCaptionsSection`) no longer needs to do
   *  any of that itself: finishing a caption pass should land the user looking at the result on the
   *  Timeline, not still sitting in the tool that started it. */
  landCaptions: (captions: CaptionSegment[], preset?: TextStylePreset, animation?: Clip["textAnimation"], fontId?: string) => void;
  /** Removes every track Auto Captions/the Script tool created (see `isAutoGeneratedCaptionsTrackName`
   *  for exactly which ones qualify — a manually renamed track is left alone), as ONE undo-able batch
   *  regardless of how many caption passes actually ran. The only way to clear a caption pass before
   *  this was deleting each generated track one at a time via its own header — fine for one pass, real
   *  friction for several. No-op (but still reports via `setStatus`) when there's nothing to clear. */
  clearCaptions: () => void;

  setStatus: (message: string | null, tone?: StatusTone) => void;
  duration: () => number;
}

/** The undo stack is intentionally NOT part of reactive state: it holds command objects with
 *  closures, it isn't serializable, and re-rendering on every push would be pointless. Only its
 *  derived booleans and labels are mirrored into the store for the UI to read. */
const undoStack = new UndoStack();

let autosaveTimer: ReturnType<typeof setTimeout> | null = null;

/** Same "not reactive state" reasoning `undoStack` above already gives — `watchAiVideo`'s own unwatch
 *  closure isn't serializable and doesn't need to trigger a re-render itself (the `aiGenerations` patch
 *  it drives already does). Single-flight (one at a time, matching `startAiVideoGeneration`'s own doc
 *  comment) is exactly why a single pair of variables is enough rather than a map keyed by job id. */
let activeAiVideoJobId: string | null = null;
let unwatchActiveAiVideo: (() => void) | null = null;

export const useEditorStore = create<EditorState>((set, get) => {
  /** Copies the undo stack's derived state into the store after any change to it. */
  function syncUndoState() {
    set({
      canUndo: undoStack.canUndo,
      canRedo: undoStack.canRedo,
      undoLabel: undoStack.undoLabel,
      redoLabel: undoStack.redoLabel,
    });
  }

  function markDirtyAndScheduleSave() {
    set({ dirty: true });
    if (autosaveTimer) clearTimeout(autosaveTimer);
    autosaveTimer = setTimeout(() => {
      void get().save();
    }, AUTOSAVE_DELAY_MS);
  }

  /** Applies a project change from an edit, keeping the playhead inside the (possibly shortened)
   *  timeline and dropping selections for clips the edit removed. */
  function applyProject(project: Project) {
    const total = sequenceDuration(project);
    const alive = new Set(project.sequence.tracks.flatMap((t) => t.clips.map((c) => c.id)));
    set((state) => ({
      project,
      playhead: Math.min(state.playhead, Math.max(0, total)),
      selectedClipIds: state.selectedClipIds.filter((id) => alive.has(id)),
      // Same reasoning as selections above: a "Remove Object" rect drawn on a clip that's since been
      // deleted has nothing left to apply to — drop it rather than leave it pointing at a dead id.
      removeObjectRect: state.removeObjectRect && !alive.has(state.removeObjectRect.clipId) ? null : state.removeObjectRect,
    }));
    markDirtyAndScheduleSave();
  }

  function patchAiGeneration(id: string, patch: Partial<AiGenerationItem>) {
    set((state) => ({ aiGenerations: state.aiGenerations.map((item) => (item.id === id ? { ...item, ...patch } : item)) }));
  }

  return {
    projectId: null,
    project: null,
    loading: true,
    loadError: null,
    loadErrorStatus: null,

    playhead: 0,
    playing: false,
    exportRangeStart: null,
    exportRangeEnd: null,
    pixelsPerSecond: DEFAULT_PIXELS_PER_SECOND,
    selectedClipIds: [],
    activeTrackId: null,
    livePreviewOverrides: [],
    groupMoveDelta: null,
    livePreviewTrackGain: null,
    livePreviewMasterGain: null,
    previewMuted: false,
    livePreviewTrackPan: null,
    playbackEngine: null,
    recording: null,
    assetDrag: null,
    contextMenu: null,
    composeText: null,
    resolveTimelineDropTarget: null,
    removeObjectArmedClipId: null,
    removeObjectRect: null,

    dirty: false,
    saving: false,
    lastSavedAt: null,

    canUndo: false,
    canRedo: false,
    undoLabel: null,
    redoLabel: null,

    status: null,
    language: readStoredLanguage(),
    importing: false,
    aiGenerations: [],
    importingSfx: false,
    importingLut: false,
    importingFont: false,
    mobileSheet: null,
    previewCanvas: null,

    async load(projectId, projectName) {
      set({ loading: true, loadError: null, loadErrorStatus: null, projectId });
      try {
        const project = await api.loadProject(projectId, projectName);
        // History from a previously-open project references clip ids that don't exist in this one.
        undoStack.clear();
        set({
          project,
          loading: false,
          dirty: false,
          playhead: 0,
          playing: false,
          exportRangeStart: null,
          exportRangeEnd: null,
          selectedClipIds: [],
          activeTrackId: project.sequence.tracks.find((t) => t.kind === "video")?.id ?? null,
          recording: null,
          // Rebuilds the AI tab's own history from whichever assets carry `aiGeneration` (see that
          // field's own doc comment) — `aiGenerations` itself doesn't persist, only the assets it once
          // produced do, so this is what makes a past generation's tile survive a reload instead of
          // looking like it vanished even though the real image/video it made never actually did.
          // Newest first, same order a fresh generation is prepended in.
          aiGenerations: project.assets
            .filter((a): a is Asset & { aiGeneration: NonNullable<Asset["aiGeneration"]> } => Boolean(a.aiGeneration))
            .sort((a, b) => b.importedAt - a.importedAt)
            .map((a) => ({
              id: a.id,
              kind: a.kind === "video" ? "video" : "image",
              prompt: a.aiGeneration.prompt,
              aspectRatio: a.aiGeneration.aspectRatio as AiAspectRatio,
              status: "done",
              asset: a,
            })),
        });
        syncUndoState();
      } catch (err) {
        set({
          loading: false,
          loadError: err instanceof Error ? err.message : String(err),
          loadErrorStatus: err instanceof ApiRequestError ? err.status : null,
        });
      }
    },

    run(command) {
      const project = get().project;
      if (!project) return;
      try {
        applyProject(undoStack.execute(project, command));
        syncUndoState();
      } catch (err) {
        // An invalid edit (split outside a clip, locked track) is normal user error, not a crash —
        // it becomes a status message and nothing changes.
        // `err.message` is translated here (not at the `EditError`/`Error` throw sites themselves) —
        // `translateText` is a plain dictionary lookup keyed by the literal English text, so a KM
        // entry for the exact message string translates it without needing to touch every file that
        // constructs one.
        if (err instanceof EditError) return get().setStatus(translateText(get().language, err.message), "error");
        throw err;
      }
    },

    undo() {
      const project = get().project;
      if (!project || !undoStack.canUndo) return;
      const label = undoStack.undoLabel;
      applyProject(undoStack.undo(project));
      syncUndoState();
      const language = get().language;
      const translatedLabel = label ? translateText(language, label) : null;
      get().setStatus(translatedLabel ? translateText(language, "Undid {label}", { label: translatedLabel }) : translateText(language, "Undone"));
    },

    redo() {
      const project = get().project;
      if (!project || !undoStack.canRedo) return;
      const label = undoStack.redoLabel;
      applyProject(undoStack.redo(project));
      syncUndoState();
      const language = get().language;
      const translatedLabel = label ? translateText(language, label) : null;
      get().setStatus(translatedLabel ? translateText(language, "Redid {label}", { label: translatedLabel }) : translateText(language, "Redone"));
    },

    async save() {
      const { project, projectId, saving } = get();
      if (!project || !projectId || saving) return;
      set({ saving: true });
      try {
        await api.saveProject(projectId, project);
        // Only clears `dirty` if nothing changed while the save was in flight — otherwise an edit
        // made mid-save would be silently marked as saved when it wasn't.
        set((state) => ({
          saving: false,
          lastSavedAt: Date.now(),
          dirty: state.project !== project,
        }));
      } catch (err) {
        set({ saving: false });
        const message = err instanceof Error ? err.message : "Could not save the project";
        get().setStatus(translateText(get().language, message), "error");
      }
    },

    setPlayhead(seconds) {
      const { project, recording } = get();
      const fps = project?.sequence.fps ?? 30;
      // A recording still in progress isn't a real clip yet (see `recording`'s own comment), so
      // `sequenceDuration` doesn't know about it — without this, `VoiceoverRecorder` driving the
      // playhead forward while capturing would get clamped right back to 0 on a still-empty project
      // (or to whatever content already ends before the take does).
      const committedTotal = project ? sequenceDuration(project) : 0;
      const liveRecordingTotal = recording ? recording.start + recording.elapsedSeconds : 0;
      const total = Math.max(committedTotal, liveRecordingTotal);
      // Allows scrubbing/playback a further `OUTRO_DURATION_SECONDS` past the real content's own end —
      // the SAME zone `Preview.tsx`'s own outro preview and `Timeline.tsx`'s own end-of-timeline marker
      // both use. Unconditional (not gated on Pro/hosted — whether THIS session will actually see an
      // outro there): keeping that plan/billing check out of a core timeline primitive that otherwise
      // has nothing to do with it outweighs the harmless cost of a Pro/local user being able to scrub a
      // couple extra seconds into empty space, the same as `Timeline.tsx`'s own `TRAILING_SECONDS` gap
      // already allows today for an unrelated reason. Without this, `PlaybackEngine` (which DOES
      // already extend its own effective duration during playback, via `getProject`'s outro-augmented
      // project) kept reporting times past `total` that this action then clamped straight back down —
      // confirmed the cause of two real, reported bugs at once: the playhead visibly never advancing
      // into the outro zone, AND the outro's own fade animation appearing to "flash"/restart, because
      // the engine's internal clock kept getting judged as having desynced from a playhead that could
      // never actually follow it past this point (see `PlaybackEngine.tick`'s own
      // `INTERNAL_CLOCK_RESYNC_TOLERANCE` comment for that resync logic).
      const outroAllowance = total > 0 ? OUTRO_DURATION_SECONDS : 0;
      set({ playhead: snapToFrame(Math.min(Math.max(0, seconds), Math.max(0, total + outroAllowance)), fps) });
    },

    setPlaying(playing) {
      set({ playing });
    },

    exportRange() {
      const { exportRangeStart, exportRangeEnd, project } = get();
      const total = project ? sequenceDuration(project) : 0;
      const clamp = (v: number) => Math.min(Math.max(0, v), Math.max(0, total));
      const a = clamp(exportRangeStart ?? 0);
      const b = clamp(exportRangeEnd ?? total);
      return a <= b ? { start: a, end: b } : { start: b, end: a };
    },

    setExportRangeStart(seconds) {
      const project = get().project;
      const fps = project?.sequence.fps ?? 30;
      set({ exportRangeStart: seconds === null ? null : snapToFrame(seconds, fps) });
    },

    setExportRangeEnd(seconds) {
      const project = get().project;
      const fps = project?.sequence.fps ?? 30;
      set({ exportRangeEnd: seconds === null ? null : snapToFrame(seconds, fps) });
    },

    clearExportRange() {
      set({ exportRangeStart: null, exportRangeEnd: null });
    },

    togglePlay() {
      const { playing, playhead, project } = get();
      if (!project) return;
      // Starting playback from the very end would look like nothing happened — rewind instead.
      if (!playing && playhead >= sequenceDuration(project) - 1e-6) set({ playhead: 0 });
      set({ playing: !playing });
    },

    stepFrames(frames) {
      const { playhead, project } = get();
      if (!project) return;
      get().setPlayhead(playhead + frames / project.sequence.fps);
    },

    setPixelsPerSecond(value) {
      set({ pixelsPerSecond: Math.min(400, Math.max(4, value)) });
    },

    zoomBy(factor) {
      get().setPixelsPerSecond(get().pixelsPerSecond * factor);
    },

    resetZoom() {
      set({ pixelsPerSecond: DEFAULT_PIXELS_PER_SECOND });
    },

    select(clipIds) {
      set({ selectedClipIds: clipIds });
    },

    toggleSelect(clipId) {
      set((state) => ({
        selectedClipIds: state.selectedClipIds.includes(clipId)
          ? state.selectedClipIds.filter((id) => id !== clipId)
          : [...state.selectedClipIds, clipId],
      }));
    },

    setLivePreviewOverrides(overrides) {
      set({ livePreviewOverrides: overrides });
    },
    setGroupMoveDelta(delta) {
      set({ groupMoveDelta: delta });
    },
    setLivePreviewTrackGain(value) {
      set({ livePreviewTrackGain: value });
    },
    setLivePreviewMasterGain(value) {
      set({ livePreviewMasterGain: value });
    },
    setLivePreviewTrackPan(value) {
      set({ livePreviewTrackPan: value });
    },
    togglePreviewMuted() {
      set((state) => ({ previewMuted: !state.previewMuted }));
    },
    setPlaybackEngine(engine) {
      set({ playbackEngine: engine });
    },
    setMobileSheet(next) {
      set({ mobileSheet: next });
    },
    setPreviewCanvas(canvas) {
      set({ previewCanvas: canvas });
    },

    setActiveTrack(trackId) {
      set({ activeTrackId: trackId });
    },

    setAssetDrag(drag) {
      set({ assetDrag: drag });
    },
    setContextMenu(menu) {
      set({ contextMenu: menu });
    },
    setComposeText(compose) {
      set({ composeText: { ...compose, content: "" } });
    },
    setComposeTextContent(content) {
      set((state) => (state.composeText ? { composeText: { ...state.composeText, content } } : {}));
    },
    commitComposedText() {
      const compose = get().composeText;
      set({ composeText: null });
      if (!compose) return;
      if (compose.content.trim() === "") return;

      const assetId = get().addTextAsset(compose.style, compose.content);
      if (!assetId) return;
      const current = get().project;
      const asset = current?.assets.find((a) => a.id === assetId);
      if (!current || !asset) return;

      const playhead = get().playhead;
      const duration = defaultClipDuration(asset);
      // A specific track (the empty-track "+" button's own case) always wins over the generic
      // fallback below — see `composeText.trackId`'s own doc comment. Otherwise, only a text track
      // with genuine room for the FULL clip AT the playhead qualifies — `nonOverlappingStart` returning
      // anything other than `playhead` itself means something on that track would get nudged out of
      // the way to fit it there instead, which read as "my text landed way past where I put the
      // playhead" (confirmed directly: a track whose next clip starts less than one default-duration
      // after the playhead was pushing the new clip all the way past it). A second, independent text
      // track (an existing empty/available one, or a freshly created one) reads as "another title
      // layer" instead, landing exactly at the playhead every time.
      const targetTrackId =
        compose.trackId ??
        current.sequence.tracks.find((t) => t.kind === "text" && !t.locked && nonOverlappingStart(t, playhead, duration) === playhead)?.id ??
        (() => {
          // AddTrackCommand exposes its trackId synchronously at construction, before it's even run —
          // so the new clip can target it directly rather than re-querying the (now-updated) project
          // for a track that was just added.
          const addTrack = new AddTrackCommand("text");
          get().run(addTrack);
          return addTrack.trackId;
        })();
      const clipId = get().addAssetAtPlayhead(assetId, targetTrackId, { avoidOverlap: true });
      if (clipId) set({ selectedClipIds: [clipId] });
    },
    cancelComposeText() {
      set({ composeText: null });
    },

    setResolveTimelineDropTarget(resolver) {
      set({ resolveTimelineDropTarget: resolver });
    },

    armRemoveObject(clipId) {
      set({ removeObjectArmedClipId: clipId });
    },

    setRemoveObjectRect(clipId, rect) {
      set({ removeObjectArmedClipId: null, removeObjectRect: { clipId, ...rect } });
    },

    clearRemoveObject() {
      set({ removeObjectArmedClipId: null, removeObjectRect: null });
    },

    async importFiles(files, options) {
      const { projectId, project } = get();
      if (!projectId || !project || files.length === 0) return [];

      set({ importing: true });
      const imported: Asset[] = [];
      const failures: string[] = [];

      // Sequential rather than parallel: each import copies a file and runs ffprobe/ffmpeg, and
      // firing a dozen of those at once would thrash the disk and spawn a dozen processes.
      for (const file of files) {
        try {
          const asset = await api.importMedia(projectId, file);
          imported.push(options?.hiddenFromLibrary ? { ...asset, hiddenFromLibrary: true } : asset);
        } catch (err) {
          failures.push(`${file.name}: ${err instanceof Error ? err.message : String(err)}`);
        }
      }

      if (imported.length > 0) {
        const current = get().project;
        if (current) {
          applyProject({ ...current, assets: [...current.assets, ...imported] });
        }
      }

      set({ importing: false });
      const language = get().language;
      if (failures.length > 0) {
        get().setStatus(
          failures.length === 1
            ? failures[0]
            : translateText(language, "{n} files could not be imported", { n: failures.length }),
          "error"
        );
      } else if (imported.length > 0) {
        get().setStatus(translateText(language, "Imported {n} file(s)", { n: imported.length }));
      }
      return imported;
    },

    async importStockResult(result) {
      const { projectId, project } = get();
      if (!projectId || !project) return null;
      set({ importing: true });
      try {
        const asset = await api.importStockResult(projectId, result);
        const current = get().project;
        if (current) applyProject({ ...current, assets: [...current.assets, asset] });
        get().setStatus(translateText(get().language, "Imported {name}", { name: asset.name }));
        return asset;
      } catch (err) {
        get().setStatus(err instanceof Error ? err.message : String(err), "error");
        return null;
      } finally {
        set({ importing: false });
      }
    },

    async generateAiImage(prompt, aspectRatio) {
      const { projectId, project } = get();
      if (!projectId || !project) return;
      const id = crypto.randomUUID();
      set((state) => ({ aiGenerations: [{ id, kind: "image", prompt, aspectRatio, status: "generating" }, ...state.aiGenerations] }));
      set({ importing: true });
      try {
        const generated = await api.generateAiImage(projectId, prompt, aspectRatio);
        // `hiddenFromLibrary`, same marker `VoiceoverRecorder`'s own takes use: a generation belongs
        // in the AI tab's own `aiGenerations` history, not duplicated into "My Media" too —
        // `addAssetAtPlayhead` is still how it reaches the timeline, exactly like a hidden voiceover
        // take does. `aiGeneration`: see its own doc comment on `Asset` — without it, `load()` below
        // has no way to tell this asset apart from a hidden voiceover take once the page reloads and
        // this in-memory `aiGenerations` list itself is gone.
        const asset = { ...generated, hiddenFromLibrary: true, aiGeneration: { prompt, aspectRatio } };
        const current = get().project;
        if (current) applyProject({ ...current, assets: [...current.assets, asset] });
        patchAiGeneration(id, { status: "done", asset });
      } catch (err) {
        patchAiGeneration(id, { status: "failed", error: err instanceof Error ? err.message : String(err) });
      } finally {
        set({ importing: false });
      }
    },

    async startAiVideoGeneration(prompt, aspectRatio) {
      const { projectId, project } = get();
      if (!projectId || !project) return;
      const id = crypto.randomUUID();
      set((state) => ({
        aiGenerations: [{ id, kind: "video", prompt, aspectRatio, status: "generating", progress: 0, stage: "" }, ...state.aiGenerations],
      }));
      try {
        const started = await api.startAiVideo(projectId, prompt, aspectRatio);
        activeAiVideoJobId = started.jobId;
        unwatchActiveAiVideo = api.watchAiVideo(
          started.jobId,
          (update: AiVideoProgress) => {
            // See `generateAiImage`'s own identical comment on `hiddenFromLibrary`/`aiGeneration` —
            // same reasoning, just for this job-based path.
            const asset = update.asset ? { ...update.asset, hiddenFromLibrary: true, aiGeneration: { prompt, aspectRatio } } : undefined;
            patchAiGeneration(id, {
              progress: update.progress,
              stage: update.stage,
              ...(update.status === "done" && asset ? { status: "done", asset } : null),
              ...(update.status === "failed"
                ? { status: "failed", error: update.error ?? translateText(get().language, "Generation failed") }
                : null),
              ...(update.status === "cancelled" ? { status: "failed", error: translateText(get().language, "Cancelled") } : null),
            });
            if (update.status === "done" && asset) {
              const current = get().project;
              if (current) applyProject({ ...current, assets: [...current.assets, asset] });
            }
            if (update.status !== "running") {
              activeAiVideoJobId = null;
              unwatchActiveAiVideo = null;
            }
          },
          (message) => {
            patchAiGeneration(id, { status: "failed", error: message });
            activeAiVideoJobId = null;
            unwatchActiveAiVideo = null;
          }
        );
      } catch (err) {
        patchAiGeneration(id, { status: "failed", error: err instanceof Error ? err.message : String(err) });
      }
    },

    cancelAiVideoGeneration() {
      // No need to also patch the item or call `unwatchActiveAiVideo` here — cancelling races the
      // job's own completion (same tolerance `cancelInpaint` already documents), and the SSE stream
      // itself delivers one final "cancelled" update through the exact same `onUpdate` handler above,
      // which already clears both module variables once `update.status !== "running"`.
      if (activeAiVideoJobId) void api.cancelAiVideo(activeAiVideoJobId);
    },

    addTextAsset(style, content = "") {
      const current = get().project;
      if (!current) return null;
      const asset = createTextAsset(content, style);
      applyProject({ ...current, assets: [...current.assets, asset] });
      return asset.id;
    },

    renameProject(name) {
      const current = get().project;
      if (!current) return;
      const trimmed = name.trim().slice(0, 120);
      const next = trimmed || "Untitled";
      if (next === current.name) return;
      applyProject({ ...current, name: next });
      get().setStatus(translateText(get().language, "Renamed project"));
    },

    landInpaintedAsset(clipId, asset) {
      get().run(new ReplaceClipAssetCommand(clipId, asset));
      get().clearRemoveObject();
      get().setStatus(translateText(get().language, 'Replaced clip with "{name}"', { name: asset.name }));
    },

    landCaptions(captions, preset, animation, fontId) {
      const current = get().project;
      if (!current || captions.length === 0) return;
      const command = new AddCaptionsCommand(captions, current.sequence.height, preset, animation, fontId);
      get().run(command);
      set({ selectedClipIds: command.clipIds, playhead: Math.max(0, captions[0].start) });
      get().setMobileSheet(null);
      get().setStatus(translateText(get().language, "Added {n} captions", { n: captions.length }));
    },

    clearCaptions() {
      const project = get().project;
      if (!project) return;
      const captionTracks = project.sequence.tracks.filter((t) => t.kind === "text" && isAutoGeneratedCaptionsTrackName(t.name));
      if (captionTracks.length === 0) {
        get().setStatus(translateText(get().language, "There are no captions to clear"));
        return;
      }
      get().run(new BatchCommand("Clear Captions", captionTracks.map((t) => new RemoveTrackCommand(t.id))));
      get().setStatus(translateText(get().language, "Cleared {n} caption track(s)", { n: captionTracks.length }));
    },

    async removeAsset(asset) {
      const { projectId, project } = get();
      if (!projectId || !project) return;

      const inUse = project.sequence.tracks.some((t) => t.clips.some((c) => c.assetId === asset.id));
      if (inUse) {
        return get().setStatus(
          translateText(get().language, "Remove that clip from the timeline before removing its media"),
          "error"
        );
      }

      try {
        await api.deleteMedia(projectId, asset);
        const current = get().project;
        if (current) applyProject({ ...current, assets: current.assets.filter((a) => a.id !== asset.id) });
        get().setStatus(translateText(get().language, "Removed {name}", { name: asset.name }));
      } catch (err) {
        const message = err instanceof Error ? err.message : "Could not remove that media";
        get().setStatus(translateText(get().language, message), "error");
      }
    },

    async importSfx(file) {
      const { projectId, project, importingSfx } = get();
      if (!projectId || !project || importingSfx) return;
      set({ importingSfx: true });
      try {
        const sfx = await api.importCustomSfx(projectId, file);
        const current = get().project;
        if (current) applyProject({ ...current, customSfx: [...current.customSfx, sfx] });
        get().setStatus(translateText(get().language, 'Added "{name}" to My Sounds', { name: sfx.label }));
      } catch (err) {
        const message = err instanceof Error ? err.message : "Could not import that sound effect";
        get().setStatus(translateText(get().language, message), "error");
      } finally {
        set({ importingSfx: false });
      }
    },

    async removeSfx(id) {
      const { projectId, project } = get();
      if (!projectId || !project) return;
      const sfx = project.customSfx.find((s) => s.id === id);
      if (!sfx) return;
      try {
        const updated = await api.deleteCustomSfx(projectId, sfx);
        applyProject(updated);
        get().setStatus(translateText(get().language, "Removed {name}", { name: sfx.label }));
      } catch (err) {
        const message = err instanceof Error ? err.message : "Could not remove that sound effect";
        get().setStatus(translateText(get().language, message), "error");
      }
    },

    async importLut(file) {
      const { projectId, project, importingLut } = get();
      if (!projectId || !project || importingLut) return;
      set({ importingLut: true });
      try {
        const lut = await api.importLut(projectId, file);
        const current = get().project;
        if (current) applyProject({ ...current, luts: [...current.luts, lut] });
        get().setStatus(translateText(get().language, 'Added "{name}" to My LUTs', { name: lut.name }));
      } catch (err) {
        const message = err instanceof Error ? err.message : "Could not import that LUT";
        get().setStatus(translateText(get().language, message), "error");
      } finally {
        set({ importingLut: false });
      }
    },

    async removeLut(id) {
      const { projectId, project } = get();
      if (!projectId || !project) return;
      const lut = project.luts.find((l) => l.id === id);
      if (!lut) return;
      try {
        const updated = await api.deleteLut(projectId, id);
        applyProject(updated);
        get().setStatus(translateText(get().language, "Removed {name}", { name: lut.name }));
      } catch (err) {
        const message = err instanceof Error ? err.message : "Could not remove that LUT";
        get().setStatus(translateText(get().language, message), "error");
      }
    },

    async importFont(file) {
      const { projectId, project, importingFont } = get();
      if (!projectId || !project || importingFont) return;
      set({ importingFont: true });
      try {
        const font = await api.importCustomFont(projectId, file);
        const current = get().project;
        if (current) applyProject({ ...current, customFonts: [...current.customFonts, font] });
        get().setStatus(translateText(get().language, 'Added "{name}" to My Fonts', { name: font.name }));
      } catch (err) {
        const message = err instanceof Error ? err.message : "Could not import that font";
        get().setStatus(translateText(get().language, message), "error");
      } finally {
        set({ importingFont: false });
      }
    },

    async removeFont(id) {
      const { projectId, project } = get();
      if (!projectId || !project) return;
      const font = project.customFonts.find((f) => f.id === id);
      if (!font) return;
      try {
        const updated = await api.deleteCustomFont(projectId, font);
        applyProject(updated);
        get().setStatus(translateText(get().language, "Removed {name}", { name: font.name }));
      } catch (err) {
        const message = err instanceof Error ? err.message : "Could not remove that font";
        get().setStatus(translateText(get().language, message), "error");
      }
    },

    addAssetAtPlayhead(assetId, trackId, options) {
      const { project, playhead, activeTrackId } = get();
      if (!project) return null;
      const asset = project.assets.find((a) => a.id === assetId);
      if (!asset) return null;

      // `trackKindForAsset` is the SAME mapping `addClip` itself enforces — reusing it here (rather
      // than re-deriving "audio/text/video" locally) is what makes double-clicking a text asset land
      // on a text track automatically, the same way it already worked for audio and video.
      const wantedKind = trackKindForAsset(asset);
      const target =
        trackId ??
        (activeTrackId && project.sequence.tracks.find((t) => t.id === activeTrackId)?.kind === wantedKind
          ? activeTrackId
          : project.sequence.tracks.find((t) => t.kind === wantedKind && !t.locked)?.id);

      if (!target) {
        const language = get().language;
        get().setStatus(
          translateText(language, "There is no unlocked {kind} track to add this to", {
            kind: translateText(language, wantedKind),
          }),
          "error"
        );
        return null;
      }

      const start = options?.avoidOverlap
        ? nonOverlappingStart(
            project.sequence.tracks.find((t) => t.id === target)!,
            playhead,
            defaultClipDuration(asset)
          )
        : playhead;
      const command = new AddClipCommand(target, assetId, start);
      get().run(command);
      return command.clipId;
    },

    duplicateSelectedClips() {
      const { selectedClipIds, language } = get();
      if (selectedClipIds.length === 0) return;
      const command = new DuplicateClipsCommand(selectedClipIds);
      get().run(command);
      const created = command.createdClipIds.length;
      if (created === 0) {
        // Every selected clip was on a locked track (or otherwise skipped) — nothing actually got
        // duplicated; say so rather than claiming success. `run` still pushed a real (no-op) undo
        // entry either way — every command does, this one included, matching e.g. deleting an
        // already-gone clip id — so there's nothing extra to clean up here.
        return get().setStatus(translateText(language, "Nothing to duplicate — every selected clip is on a locked track"), "error");
      }
      set({ selectedClipIds: command.createdClipIds });
      get().setStatus(created === 1 ? translateText(language, "Duplicated clip") : translateText(language, "Duplicated {n} clips", { n: created }));
    },

    extractAudioFromClip(clipId) {
      const { language, projectId } = get();
      const command = new ExtractAudioCommand(clipId);
      get().run(command);
      set({ selectedClipIds: [command.newClipId] });
      get().setStatus(translateText(language, "Extracted audio"));

      // The clip already plays correctly at this point (see `ExtractAudioCommand`'s own doc comment —
      // audio playback only cares about `track.kind`, not the asset's) — this is a purely cosmetic
      // upgrade running in the background: derive a genuinely independent audio file/asset server-side
      // so the Media library and this clip's own thumbnail stop showing the ORIGINAL video's filename
      // and film-strip (a real, reported confusion — see `extractAudioAsset`'s own doc comment).
      // Silently skipped wherever there's no server to ask (native) or nothing to ask it about (the
      // original asset has no backing file, e.g. an already-synthetic clip — shouldn't happen for a
      // video-track clip, but this stays a pure enhancement either way, never required for correctness).
      const newClipId = command.newClipId;
      const project = get().project;
      const originalAsset = project ? findAsset(project, findClip(project, clipId)?.clip.assetId ?? "") : undefined;
      if (!projectId || !originalAsset?.relPath) return;
      void api
        .extractAudioAsset(projectId, originalAsset.relPath, originalAsset.name)
        .then((asset) => {
          if (!asset) return;
          const current = get().project;
          if (!current || !findClip(current, newClipId)) return; // clip deleted meanwhile
          get().run(new SwapClipAssetCommand(newClipId, asset));
        })
        .catch(() => {
          // Silent — see this block's own opening comment for why a failure here isn't worth surfacing.
        });
    },

    applyTextStylePresetToSelection(preset) {
      const { project, selectedClipIds, language } = get();
      if (!project) return;
      const command = buildTextStylePresetCommand(project, selectedClipIds, preset);
      if (!command) return;
      get().run(command);
      get().setStatus(translateText(language, "Applied style"));
    },

    applyTextAnimationToSelection(animation) {
      const { project, selectedClipIds, language } = get();
      if (!project) return;
      const command = buildTextAnimationCommand(project, selectedClipIds, animation);
      if (!command) return;
      get().run(command);
      get().setStatus(translateText(language, "Applied animation"));
    },

    patchTextStyleForSelection(patch) {
      const { project, selectedClipIds } = get();
      if (!project) return;
      const command = buildTextStylePatchCommand(project, selectedClipIds, patch);
      if (!command) return;
      get().run(command);
    },

    beginRecordingIndicator(trackId, start) {
      set({ recording: { trackId, start, elapsedSeconds: 0, phase: "recording" } });
    },
    updateRecordingElapsed(elapsedSeconds) {
      set((state) => (state.recording ? { recording: { ...state.recording, elapsedSeconds } } : {}));
    },
    finalizeRecordingIndicator() {
      set((state) => (state.recording ? { recording: { ...state.recording, phase: "finalizing" } } : {}));
    },
    clearRecordingIndicator() {
      set({ recording: null });
    },
    pickVoiceoverTrack() {
      const project = get().project;
      if (!project) return null;
      const audioTracks = project.sequence.tracks.filter((t) => t.kind === "audio" && !t.locked);
      const empty = audioTracks.find((t) => t.clips.length === 0);
      if (empty) return empty.id;
      // "Already holds a prior recording" — grouping takes together rather than landing a voiceover in
      // whatever unlocked audio track happens to be first (which might be a music/SFX track instead).
      // `hiddenFromLibrary` is the same marker `VoiceoverRecorder` stamps on a take's asset to keep it
      // out of the Media Library — reused here as a reliable "this clip came from a recording" signal,
      // rather than pattern-matching the asset's (user-renamable) display name.
      const hasVoiceover = audioTracks.find((t) =>
        t.clips.some((c) => project.assets.find((a) => a.id === c.assetId)?.hiddenFromLibrary)
      );
      if (hasVoiceover) return hasVoiceover.id;
      return audioTracks[0]?.id ?? null;
    },
    beginVoiceoverRecording() {
      if (!get().project) return null;
      let trackId = get().pickVoiceoverTrack();
      if (!trackId) {
        const addTrack = new AddTrackCommand("audio");
        get().run(addTrack);
        trackId = addTrack.trackId;
      }
      const track = get().project?.sequence.tracks.find((t) => t.id === trackId);
      if (!track) return null;
      const start = nonOverlappingPointStart(track, get().playhead);
      get().beginRecordingIndicator(trackId, start);
      return { trackId, start };
    },

    addColorAtPlayhead(color) {
      const current = get().project;
      if (!current) return;
      const asset = createColorAsset(color);
      applyProject({ ...current, assets: [...current.assets, asset] });

      const existingTrack = current.sequence.tracks.find((t) => t.kind === "video" && !t.locked);
      if (existingTrack) {
        get().addAssetAtPlayhead(asset.id, existingTrack.id, { avoidOverlap: true });
      } else {
        const addTrack = new AddTrackCommand("video");
        get().run(addTrack);
        get().addAssetAtPlayhead(asset.id, addTrack.trackId, { avoidOverlap: true });
      }
      get().setStatus(translateText(get().language, "Added background color"));
    },

    setStatus(message, tone = "info") {
      set({ status: message ? { message, tone } : null });
    },

    setLanguage(language) {
      set({ language });
      try {
        window.localStorage.setItem(LANGUAGE_STORAGE_KEY, language);
      } catch {
        // Private-mode/disabled storage — the toggle still works for this session, it just won't
        // survive a reload. Not worth surfacing as an error over a UI preference.
      }
    },

    duration() {
      const project = get().project;
      return project ? sequenceDuration(project) : 0;
    },
  };
});

/** Flushes any pending autosave immediately — used when the editor unmounts or the window is about
 *  to close, so the debounce window can't swallow the last edit. */
export async function flushPendingSave(): Promise<void> {
  if (autosaveTimer) {
    clearTimeout(autosaveTimer);
    autosaveTimer = null;
  }
  const state = useEditorStore.getState();
  if (state.dirty) await state.save();
}
