"use client";

import { useEffect, useRef, useState } from "react";
import { createPortal } from "react-dom";
import {
  cancelCaptions,
  captionsAvailable,
  CAPTION_LANGUAGE_OPTIONS,
  getInpaintKeyStatus,
  setInpaintApiKey,
  startCaptions,
  watchCaptions,
  type InpaintKeyStatus,
  type CaptionsProgress,
} from "../api/client.ts";
import type { Clip } from "../project/types.ts";
import type { TextStylePreset } from "../project/textStylePresets.ts";
import { startCheckout } from "../api/billing.ts";
import { extractCaptionCues, parseCaptionFile, serializeSrt, serializeVtt } from "../captions/captionFormats.ts";
import { useTranslation } from "../i18n/useTranslation.ts";
import { useEditorStore } from "../store/editorStore.ts";
import { isAutoGeneratedCaptionsTrackName } from "../commands/index.ts";
import { ConfirmDialog } from "./ConfirmDialog.tsx";
import { Dropdown } from "./Dropdown.tsx";
import { defaultFontIdFor, FontPickerGrid } from "./FontPickerGrid.tsx";
import { PickerTabs } from "./PickerTabs.tsx";
import { TextAnimationPickerGrid } from "./TextAnimationPickerGrid.tsx";
import { TextStylePresetGrid } from "./TextStylePresetGrid.tsx";
import { useHostedCreditsGate } from "./useHostedCreditsGate.ts";
import { useVisualViewportHeight } from "./useVisualViewportHeight.ts";

type Phase = "idle" | "running" | "failed" | "cancelled";
type PickerTab = "font" | "style" | "animation";

/** Auto Captions, as a modal — the toolbar's entry point either way: whole-sequence with nothing
 *  selected, or scoped to the selected clip(s) (`clipIds` set) the moment one or more clips with audio
 *  ARE selected — see `VCutApp.tsx`'s own Captions button for exactly how that choice gets made. A
 *  modal for BOTH cases now, not just the whole-sequence one: Inspector's inline `AutoCaptionsSection`
 *  still exists and still works for the single-clip case (nothing here replaces it), but reaching it
 *  meant landing on Inspector — already visible on desktop, requiring the right tab found once there
 *  either way — and a second tap into the mobile sheet, versus this dialog's single, direct click on
 *  both. Same `api/client.ts` functions and the same `landCaptions` store action either scope runs
 *  underneath — `startCaptions`'s own optional `clipIds` parameter is the entire difference; several
 *  ids (a multi-clip selection — e.g. one long voiceover trimmed into several pieces) transcribe as ONE
 *  combined, gap-skipping pass rather than needing to be run one at a time (see that function's own
 *  doc comment). */
export function AutoCaptionsDialog({ onClose, clipIds }: { onClose: () => void; clipIds?: string[] }) {
  const t = useTranslation();
  const projectId = useEditorStore((s) => s.projectId);
  const save = useEditorStore((s) => s.save);
  const landCaptions = useEditorStore((s) => s.landCaptions);
  const clearCaptions = useEditorStore((s) => s.clearCaptions);
  const hasClipSelection = Boolean(clipIds && clipIds.length > 0);
  // Only counts tracks a PREVIOUS caption/Script pass actually created (see
  // `isAutoGeneratedCaptionsTrackName`'s own doc comment) — the "Clear existing captions" link below
  // only shows up when there's genuinely something for it to do. Never shown at all when scoped to a
  // clip selection (`clipIds` set) — clearing EVERY caption track in the project is a mismatched,
  // surprising action to offer from what reads as a selection-scoped tool.
  const hasExistingCaptions = useEditorStore(
    (s) => !hasClipSelection && (s.project?.sequence.tracks.some((t) => t.kind === "text" && isAutoGeneratedCaptionsTrackName(t.name)) ?? false)
  );
  const [confirmingClear, setConfirmingClear] = useState(false);
  const viewportHeight = useVisualViewportHeight();

  // Whole-project actions, same "never shown scoped to a clip selection" reasoning as
  // `hasExistingCaptions` above — exporting/importing an SRT file is inherently about the whole
  // timeline's own caption clips, not one clip's audio. Unlike `hasExistingCaptions`, this counts
  // EVERY text track's clips (see `extractCaptionCues`'s own doc comment), not just auto-generated
  // ones — a hand-authored caption track is just as real a thing to export.
  const exportableCueCount = useEditorStore((s) => (!hasClipSelection && s.project ? extractCaptionCues(s.project).length : 0));
  const importInputRef = useRef<HTMLInputElement | null>(null);

  const [available, setAvailable] = useState<boolean | null>(null);
  // Shared with `RemoveObjectSection` (Inspector.tsx) — Captions runs on the SAME saved Replicate
  // token, not a captions-specific credential, so this checks `configured.replicate` rather than a
  // separate status type. See `_lib/inpaintEnvFile.ts`'s `getReplicateToken` for why.
  const [status, setStatus] = useState<InpaintKeyStatus | null>(null);
  const [keyInput, setKeyInput] = useState("");
  const [savingKey, setSavingKey] = useState(false);
  // In hosted mode there's no per-user key to configure at all (VCut supplies one server-owned
  // Replicate token — see `_lib/inpaintEnvFile.ts`'s own `VCUT_HOSTED` branch) and `inpaint/settings`
  // (GET, the thing `status` above comes from) stays 403'd there on purpose, so `status` would
  // otherwise be stuck permanently `null` for every hosted user — `hosted` is what lets the render
  // logic below skip past that check entirely instead of getting stuck on "Checking…" forever.
  // `credits` is the hosted-only replacement gate: `available` alone already reflects whether the
  // server token is configured.
  const { hosted, credits } = useHostedCreditsGate();
  const outOfCredits = hosted && credits !== null && credits.creditsRemaining <= 0;

  const [preset, setPreset] = useState<TextStylePreset | null>(null);
  const [animation, setAnimation] = useState<Clip["textAnimation"] | null>(null);
  // `null` = "follow the language's own default" (see `defaultFontIdFor`); a tile click sets an
  // explicit override. Reset back to `null` whenever `language` changes (below) — a font picked while
  // one language was selected can easily have no glyphs at all for a different one (Khmer-only display
  // faces most of all), so carrying a manual choice across a language switch would be actively wrong,
  // not just stale, unlike `preset`/`animation` which stay sticky across a language change on purpose.
  const [fontId, setFontId] = useState<string | null>(null);
  const [language, setLanguage] = useState("auto");
  const [pickerTab, setPickerTab] = useState<PickerTab>("font");
  const [phase, setPhase] = useState<Phase>("idle");
  const [stage, setStage] = useState<string>("");
  const [progress, setProgress] = useState(0);
  const [error, setError] = useState<string | null>(null);
  const jobIdRef = useRef<string | null>(null);
  const unwatchRef = useRef<(() => void) | null>(null);

  useEffect(() => {
    void captionsAvailable().then(setAvailable);
    void getInpaintKeyStatus().then(setStatus);
  }, []);

  useEffect(() => setFontId(null), [language]);

  useEffect(() => () => unwatchRef.current?.(), []);

  useEffect(() => {
    function onKeyDown(e: KeyboardEvent) {
      if (e.key === "Escape" && phase !== "running") onClose();
    }
    window.addEventListener("keydown", onKeyDown);
    return () => window.removeEventListener("keydown", onKeyDown);
  }, [phase, onClose]);

  async function handleSaveKey() {
    if (!keyInput.trim()) return;
    setSavingKey(true);
    try {
      await setInpaintApiKey("replicate", keyInput);
      setKeyInput("");
      setStatus(await getInpaintKeyStatus());
      setAvailable(await captionsAvailable());
    } catch {
      setError(t("Couldn't save that API key"));
    } finally {
      setSavingKey(false);
    }
  }

  async function begin() {
    if (!projectId) return;
    setError(null);
    setProgress(0);
    setStage("");
    setPhase("running");
    // Same reasoning as the per-clip section's own `await save()` first — the server transcribes the
    // SAVED project file, so unsaved edits would otherwise be silently ignored.
    await save();
    try {
      const started = await startCaptions(projectId, clipIds, language, animation?.type === "wordHighlight");
      jobIdRef.current = started.jobId;
      unwatchRef.current = watchCaptions(
        started.jobId,
        (update: CaptionsProgress) => {
          setStage(update.stage);
          setProgress(update.progress);
          if (update.status === "done") {
            if (update.captions) landCaptions(update.captions, preset ?? undefined, animation ?? undefined, fontId ?? defaultFontIdFor(language));
            onClose();
          } else {
            setPhase(update.status);
          }
          if (update.status === "failed" && update.error) setError(update.error);
        },
        (message) => setError(message)
      );
    } catch (err) {
      setPhase("failed");
      setError(err instanceof Error ? err.message : t("Could not start the job"));
    }
  }

  function stop() {
    if (jobIdRef.current) void cancelCaptions(jobIdRef.current);
    setPhase("cancelled");
  }

  /** Pure client-side — `extractCaptionCues`/`serializeSrt`/`serializeVtt` only ever read the in-memory
   *  `project`, no server round-trip needed (unlike the video export this dialog is NOT the same
   *  feature as). Reads `project` fresh via `getState()` at click time rather than a subscribed value —
   *  this only ever runs from a user click, so there's nothing to keep reactive between renders, and a
   *  stale closed-over `project` from an earlier render would risk exporting a project a save/undo has
   *  since replaced. A temporary, never-appended-to-the-visible-DOM `<a download>` is the standard way
   *  to trigger a same-origin blob download without navigating the page away from this dialog. */
  function downloadCaptions(format: "srt" | "vtt") {
    const currentProject = useEditorStore.getState().project;
    if (!currentProject) return;
    const cues = extractCaptionCues(currentProject);
    if (cues.length === 0) return;
    const content = format === "srt" ? serializeSrt(cues) : serializeVtt(cues);
    const blob = new Blob([content], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${currentProject.name || "captions"}.${format}`;
    a.click();
    URL.revokeObjectURL(url);
  }

  /** Lands an imported SRT/VTT file through the EXACT same `landCaptions` path a finished transcription
   *  job uses (see `begin`'s own `landCaptions` call above) — same undo-able `AddCaptionsCommand`, same
   *  "apply the Font/Style/Animation tabs' current picks to the whole batch" behavior, so an imported
   *  file benefits from styling choices exactly like a generated one would, with no separate landing
   *  code to keep in sync. `e.target.value = ""` first so choosing the SAME file again later (after
   *  fixing something in it, say) still fires `onChange` — a bare file input only fires on a CHANGE in
   *  its own value, which re-picking the identical file would otherwise never produce. */
  async function handleImportFile(e: React.ChangeEvent<HTMLInputElement>) {
    const file = e.target.files?.[0];
    e.target.value = "";
    if (!file) return;
    setError(null);
    try {
      const text = await file.text();
      const cues = parseCaptionFile(text);
      if (cues.length === 0) {
        setError(t("Couldn't find any captions in that file"));
        return;
      }
      landCaptions(
        cues.map((c) => ({ content: c.text, start: c.start, end: c.end })),
        preset ?? undefined,
        animation ?? undefined,
        fontId ?? defaultFontIdFor(language)
      );
      onClose();
    } catch {
      setError(t("Couldn't read that file"));
    }
  }

  // `null` in hosted mode — there's no per-user key to configure at all there (see `hosted`'s own
  // comment above), so this whole block simply never applies. No provider dropdown (unlike Remove
  // Object's own equivalent in Inspector.tsx) — Captions only ever runs on Replicate, there's nothing
  // to choose. Saving here activates Replicate as Remove Object's own active provider too (same
  // `setInpaintApiKey` call its own key-entry form uses) since it's the same one saved token either
  // way — entering it from whichever feature you reach first is enough for both.
  const credentialsBlock = !hosted && status && (
    <div className="mb-3 space-y-1.5">
      <p className="text-[11px] text-white/35">
        {status.configured.replicate ? t("Using your saved Replicate key.") : t("No Replicate key saved yet.")}
      </p>
      <div className="flex gap-2">
        <input
          type="password"
          value={keyInput}
          onChange={(e) => setKeyInput(e.target.value)}
          placeholder={status.configured.replicate ? t("Paste a new key to replace the saved one") : t("Replicate API key")}
          className="min-w-0 flex-1 rounded bg-white/5 px-2.5 py-1.5 text-[12px] text-white placeholder:text-white/30 focus:outline-none focus:ring-1 focus:ring-sky-400/60"
        />
        <button
          onClick={() => void handleSaveKey()}
          disabled={savingKey || !keyInput.trim()}
          className="shrink-0 rounded bg-sky-500 px-3 py-1.5 text-[12px] font-medium text-white transition hover:bg-sky-400 disabled:opacity-50"
        >
          {savingKey ? t("Saving…") : status.configured.replicate ? t("Replace") : t("Save")}
        </button>
      </div>
    </div>
  );

  const languagePicker = (
    <div className="mb-3 flex items-center justify-between gap-2">
      <span className="text-[11px] text-white/35">{t("Spoken language")}</span>
      <Dropdown
        value={language}
        options={CAPTION_LANGUAGE_OPTIONS.map((o) => ({ value: o.code, label: t(o.label) }))}
        onChange={setLanguage}
        ariaLabel={t("Spoken language")}
        disabled={phase === "running"}
        className="w-36 text-[11px]"
      />
    </div>
  );

  return (
    <>
      {createPortal(
        <div
          className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-4"
          onClick={() => phase !== "running" && onClose()}
          role="dialog"
          aria-modal="true"
          aria-label={t("Auto Captions")}
        >
      {/* `flex flex-col` — title fixed at top, footer buttons fixed at bottom (both `shrink-0`),
          Language/Style/Animation in their own `overflow-y-auto` middle section: on a short phone that
          combination can run taller than the viewport, and without a scrollable region ANYWHERE the
          Cancel/Generate buttons below the fold would simply be unreachable. Height capped against
          `useVisualViewportHeight` rather than a `max-h-[90vh]` class — see that hook's own doc
          comment: a `vh` unit keeps assuming the full, un-shrunk viewport is available even when it
          isn't (an on-screen keyboard from the credentials field below, or simply mobile Safari's own
          dynamic browser chrome being visible), which is what let content below the fold end up
          genuinely unreachable rather than merely needing a scroll. Same fix as
          `TextToClipsDialog.tsx`'s identical structure. */}
      <div
        onClick={(e) => e.stopPropagation()}
        style={{ maxHeight: Math.max(240, viewportHeight - 32) }}
        className="flex w-full max-w-sm flex-col rounded-xl border border-white/10 bg-[#12151c] p-5 shadow-2xl"
      >
        <h2 className="flex shrink-0 items-center gap-1.5 text-sm font-semibold text-white">
          {t("Auto Captions")}
          {/* Same hosted-only, credit-metered "PRO" badge as the toolbar button that opens this
              dialog and Inspector's own equivalent section — see `VCutApp.tsx`'s `ToolbarButton`
              for the full reasoning. */}
          {hosted && <span className="rounded-sm bg-amber-400 px-1 text-[9px] font-bold leading-tight tracking-wide text-black">PRO</span>}
        </h2>
        <p className="mt-2 shrink-0 text-xs leading-relaxed text-white/60">
          {!hasClipSelection
            ? t("Transcribes the whole sequence's audio and adds the result as editable caption clips on a new track.")
            : clipIds!.length === 1
              ? t("Transcribes this clip's audio and adds the result as editable caption clips on a new track.")
              : t("Transcribes the selected clips' audio as one combined pass and adds the result as editable caption clips on a new track.")}
        </p>
        {/* Only ever removes tracks a caption/Script pass itself created (see
            `isAutoGeneratedCaptionsTrackName`) — previously the only way to start over was deleting
            each generated track one at a time via its own header, real friction after more than one
            pass. Outside the scrollable middle section, same as the title/description, so it's always
            reachable without scrolling. */}
        {hasExistingCaptions && (
          <button
            onClick={() => setConfirmingClear(true)}
            className="mt-2 shrink-0 self-start text-[11px] font-medium text-rose-300/80 transition hover:text-rose-200"
          >
            {t("Clear existing captions")}
          </button>
        )}

        {/* SRT/VTT round-trip — see captions/captionFormats.ts's own top-of-file comment for the "what
            is/isn't preserved" scope. Whole-project actions, same "never shown scoped to a clip
            selection" reasoning as `hasExistingCaptions` above (`exportableCueCount` is already forced
            to 0 in that case). Import has nothing to gate on beyond that — unlike Generate, it needs no
            server feature/credits check at all, so it's placed here rather than down in the footer
            alongside the Generate button whose availability checks don't apply to it. */}
        {!hasClipSelection && (
          <div className="mt-2 flex shrink-0 flex-wrap items-center gap-x-3 gap-y-1">
            {exportableCueCount > 0 && (
              <>
                <button
                  onClick={() => downloadCaptions("srt")}
                  className="text-[11px] font-medium text-white/50 transition hover:text-white/80"
                >
                  {t("Export SRT")}
                </button>
                <button
                  onClick={() => downloadCaptions("vtt")}
                  className="text-[11px] font-medium text-white/50 transition hover:text-white/80"
                >
                  {t("Export VTT")}
                </button>
              </>
            )}
            <button
              onClick={() => importInputRef.current?.click()}
              className="text-[11px] font-medium text-white/50 transition hover:text-white/80"
            >
              {t("Import SRT/VTT…")}
            </button>
            <input ref={importInputRef} type="file" accept=".srt,.vtt,text/plain" className="hidden" onChange={(e) => void handleImportFile(e)} />
          </div>
        )}

        {/* `scrollbar-none` (see globals.css) — a visible OS scrollbar chrome here would be the only
            scrollbar anywhere in a modal this size, reading as a stray UI element rather than an
            intentional affordance; the content itself (and simply being able to swipe) already makes
            it obvious there's more below. `px-1`/`-mx-1`: a focused input's or a selected preset's own
            `ring-1` sits 1px OUTSIDE its element's box via `box-shadow`, and setting `overflow-y` to
            anything but `visible` here forces `overflow-x` to compute as `auto` too (the CSS Overflow
            spec's own interaction rule, not a mistake) — with zero horizontal padding to spare, that
            silently clipped the ring right off the left/right edges. The `-mx-1` cancels the padding's
            own width impact so children stay visually flush with the title/description above. */}
        <div className="-mx-1 mt-4 min-h-0 flex-1 overflow-y-auto scrollbar-none px-1">
          {/* `status` stays permanently `null` in hosted mode (its own settings route 403s there —
              nothing to fetch) — `hosted` is what lets this move past "Checking…" using `available`
              alone instead of waiting on a value that will never arrive. */}
          {available === null || (!hosted && status === null) ? (
            <p className="text-[12px] text-white/35">{t("Checking…")}</p>
          ) : !hosted && !status?.configured.replicate ? (
            credentialsBlock
          ) : !available ? (
            <>
              {credentialsBlock}
              <p className="text-[12px] leading-relaxed text-rose-300">{t("FFmpeg isn't available — reinstall dependencies to use this.")}</p>
            </>
          ) : outOfCredits ? (
            <>
              <p className="text-[12px] leading-relaxed text-amber-300">
                {t("You're out of credits for this month — upgrade to Pro for more, or wait for your credits to refill.")}
              </p>
              <button
                onClick={() => void startCheckout().then((url) => (window.location.href = url))}
                className="mt-2 w-full rounded bg-sky-500 py-1.5 text-[12px] font-medium text-white transition hover:bg-sky-400"
              >
                {t("Upgrade to Pro")}
              </button>
            </>
          ) : phase === "running" ? (
            <>
              {credentialsBlock}
              <p className="text-[12px] text-white/60 capitalize">{(stage || t("Starting…")).replaceAll("-", " ")}</p>
              <div className="mt-1.5 h-1.5 w-full overflow-hidden rounded-full bg-white/10">
                <div className="h-full rounded-full bg-sky-400 transition-all" style={{ width: `${Math.round(progress * 100)}%` }} />
              </div>
            </>
          ) : (
            <>
              {credentialsBlock}
              {languagePicker}
              {/* All three tabs are "chosen up front" — the whole batch of captions this job produces
                  lands already looking/animated/fonted this way, rather than a fixed default that then
                  needs restyling clip by clip (or via the toolbar's own bulk tools) afterward. Split
                  into tabs, not stacked, specifically because Font alone can run up to ~25 tiles for
                  Khmer — three full grids stacked in this already-tight scrollable section would be
                  far more scrolling than picking one tab at a time. */}
              <PickerTabs
                tabs={[
                  { id: "font", label: t("Font") },
                  { id: "style", label: t("Style") },
                  { id: "animation", label: t("Animation") },
                ]}
                active={pickerTab}
                onChange={setPickerTab}
              />
              {/* Own capped-height scroll region, independent of the dialog's outer one — Font alone can
                  run ~25 tiles for Khmer, and without this a tall tab's content would otherwise grow the
                  WHOLE middle section (this dialog's footer is fixed outside it so Generate stays
                  reachable either way, but `AutoCaptionsSection`'s own copy of this same UI in Inspector
                  has no such fixed footer — there, an uncapped grid really did push its own Generate
                  button far down a long scroll). Fixed height (not content-dependent) also means
                  switching tabs never resizes the dialog around the user. */}
              <div className="max-h-52 overflow-y-auto scrollbar-none pr-0.5">
                {pickerTab === "font" && (
                  <FontPickerGrid khmerOnly={language === "km"} selectedId={fontId ?? defaultFontIdFor(language)} onPick={setFontId} />
                )}
                {pickerTab === "style" && (
                  <>
                    <button
                      onClick={() => setPreset(null)}
                      className={`mb-1.5 w-full rounded bg-white/5 py-1.5 text-[12px] text-white/70 transition hover:bg-white/10 hover:text-white ${
                        preset === null ? "ring-1 ring-sky-400/60" : ""
                      }`}
                    >
                      {t("Default")}
                    </button>
                    <TextStylePresetGrid selectedId={preset?.id} onPick={setPreset} />
                  </>
                )}
                {pickerTab === "animation" && <TextAnimationPickerGrid current={animation} onPick={setAnimation} />}
              </div>
            </>
          )}
          {error && <p className="mt-2 text-[12px] text-rose-300">{error}</p>}
        </div>

        <div className="mt-5 flex shrink-0 items-center justify-end gap-2">
          <button
            onClick={phase === "running" ? stop : onClose}
            className="rounded-md px-3 py-1.5 text-xs font-medium text-white/60 transition hover:bg-white/10 hover:text-white"
          >
            {phase === "running" ? t("Cancel") : t("Close")}
          </button>
          {phase !== "running" && available && (hosted || status?.configured.replicate) && !outOfCredits && (
            <button
              onClick={() => void begin()}
              className="rounded-md bg-sky-500 px-4 py-1.5 text-xs font-semibold text-white transition hover:bg-sky-400"
            >
              {t("Generate Captions")}
            </button>
          )}
        </div>
      </div>
        </div>,
        document.body
      )}
      {confirmingClear && (
        <ConfirmDialog
          title={t("Clear existing captions?")}
          message={t("This removes every track a previous captions pass created. You can undo it with Ctrl/⌘+Z.")}
          confirmLabel={t("Clear captions")}
          onConfirm={() => {
            setConfirmingClear(false);
            clearCaptions();
          }}
          onCancel={() => setConfirmingClear(false)}
        />
      )}
    </>
  );
}
